### ISSUE TITLE
How to directly update haproxy config file from the HAProxyHQ backend

### ISSUE THREAD

**Issue by SyCode7** [haproxyhq/backend#3]
Hi guys,

Firstly, like to thanks you for the wonderful job you have done in the development  of 'the HAProxyHQ. I have installed the application and it works well in my small development setup. The challenge I have currently is how to modify the haproxy configuration file from the backend (spring application). Since I am still new to java and much newer to spring it is a bit difficult to identify the correct classes to call especially as there are no test classes. So far I am thinking that if I directly modify the db in mongodb the agent might push the changes to the server, I am still testing if this works though. I will really appreciate any direction from you.

Many thanks for your candid assistance.

**Comment by buettner123** [comment]
Hi,
sorry for the missing tests. It was a small project at the university with a fixed time span on it..
To answer your question:
You can find the model itself here: https://github.com/haproxyhq/backend/blob/master/src/main/java/de/haproxyhq/nosql/model/Schema.java
To update it from the backend application you can use the schema repository (just autowire it where you need it):
https://github.com/haproxyhq/backend/blob/master/src/main/java/de/haproxyhq/nosql/repositories/SchemaRepository.java
I hope this answers your question!

**Comment by SyCode7** [comment]
@buettner123  great, your response was quite helpful. But now i get a ` java.lang.NullPointerExceptio`  after autowiring as you mentioned. See my code snippet below :

`	@Autowired
	static SchemaRepository schemaRepository;
	static Schema schema = new Schema();
	
	public static void main(String[] args) {
		System.out.println(schemaRepository.findOne("586b9b2c10f97f8180eb78f4"));

I think I need to authenticate somehow, can you guide me how or maybe provide a small code snippet ?
Thanks.

**Comment by buettner123** [comment]
Please read some documentations about spring and how autowiring works.
There is no need to authenticate as long as you are using the repository from the same application.

As a hint to your problem: It is not possible to autowire static fields in spring. You should think of moving your code to a own class/function and call it from the App context instead of the static main context

**Comment by jdepoix** [comment]
@SyCode7 Hey,
you can not autowire static fields ([for good reasons](https://stackoverflow.com/questions/10938529/why-cant-we-autowire-static-fields-in-spring)).
Don't get me wrong, I don't want to discourage you from working on HAProxyHQ and learning more about Spring and Java, but the purpose of this Issue section is to report problems related to the project, rather than discussing general programming questions. If you want to learn more about Java and Spring, or find help with problems like these, I'd highly recommend [Stackoverflow](https://stackoverflow.com/questions/tagged/spring)! You'll find an answer to almost every question you could possibly have there :)

**Comment by SyCode7** [comment]
@buettner123 @jdepoix  my apologies for using this space to ask my noobish questions and I appreciate your responses. I will try out with the App context within the backend application ... hope it works.
